// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppnulxweiiczciuxcypn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwbnVseHdlaWljemNpdXhjeXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMzg3NDAsImV4cCI6MjA1ODYxNDc0MH0.qFMUbh8JFO-lyiWTp-9EXG4lKwPR5Gy4nmGEzfX3CNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);