name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows the workflow to be manually triggered from the GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_INSTANCE_SG_ID: ${{ secrets.AWS_INSTANCE_SG_ID }}
      SMTP_API_KEY: ${{ secrets.SMTP_API_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
    steps:
      # Set up repository and environment
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js and pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.4
          run_install: false

      # Build application
      - name: Install dependencies
        run: |
          # Install all dependencies explicitly for the workspace root
          pnpm install -w
          # Ensure platform-specific packages are installed at workspace root
          pnpm install @swc/core@latest --save-dev -w
          pnpm install @swc/core-linux-x64-gnu @esbuild/linux-x64 --save-optional -w

      - name: Build application and populate static assets
        run: |
          echo "Build environment:"
          echo "Current directory: $(pwd)"
          echo "Starting build..."
          cd apps/web
          pnpm run prepare-deploy
          echo "Deployment package created"

      # Configure AWS and secure SSH access
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get GitHub runner's public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Whitelist GitHub runner's IP in EC2 security group
        run: |
          echo "Adding IP ${{ steps.ip.outputs.ipv4 }} to security group $AWS_INSTANCE_SG_ID"
          aws ec2 authorize-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
      # First SSH connection to set up GitHub authentication
      - name: Set up GitHub authentication on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.RB_EC2_KEY }}
          port: 22
          command_timeout: "10m"
          script: |
            # Set up GitHub authentication using deploy key
            mkdir -p ~/.ssh
            echo "${{ secrets.REPO_DEPLOY_KEY }}" > ~/.ssh/github_deploy_key
            chmod 600 ~/.ssh/github_deploy_key
            # Configure SSH to use the key for GitHub
            cat > ~/.ssh/config << EOF
            Host github.com
              HostName github.com
              User git
              IdentityFile ~/.ssh/github_deploy_key
              IdentitiesOnly yes
            EOF
            # Add GitHub to known hosts to avoid prompts
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            # Test GitHub SSH connection
            ssh -T -o StrictHostKeyChecking=no git@github.com || echo "GitHub authentication configured"
      # Main deployment script
      - name: Deploy application to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.RB_EC2_KEY }}
          port: 22
          command_timeout: "20m"
          script: |
            # Create deployment directory
            mkdir -p /home/ec2-user/app
            echo "Deployment directory created"

      # Copy the deployment package to EC2
      - name: Copy deployment package to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.RB_EC2_KEY }}
          port: 22
          source: "apps/web/deploy/deploy-*.zip"
          target: "/home/ec2-user/app"
          overwrite: true

      # Extract and run the application on EC2
      - name: Extract and run application
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.RB_EC2_KEY }}
          port: 22
          command_timeout: "10m"
          script: |
            # Navigate to app directory
            cd /home/ec2-user/app

            # Get the latest deployment package
            LATEST_PACKAGE=$(ls -t deploy-*.zip | head -1)
            echo "Latest deployment package: $LATEST_PACKAGE"

            # Stop the running application if it exists
            echo "Stopping any running application..."
            pm2 stop nextjs-app || true

            # Create a clean deployment directory
            echo "Preparing deployment directory..."
            rm -rf deploy-latest
            mkdir -p deploy-latest

            # Extract the deployment package
            echo "Extracting deployment package..."
            unzip -o "$LATEST_PACKAGE" -d deploy-latest

            # Make the run script executable
            chmod +x deploy-latest/run.sh

            # Set environment variables
            echo "Setting environment variables..."
            cat > deploy-latest/.env <<EOF
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
            SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
            SUPABASE_JWT_SECRET=${{ secrets.SUPABASE_JWT_SECRET }}
            SMTP_API_KEY=${{ secrets.SMTP_API_KEY }}
            NODE_ENV=production
            PORT=3000
            EOF

            # Start the application with PM2
            echo "Starting application with PM2..."
            cd deploy-latest
            pm2 start server.js --name nextjs-app

            echo "Deployment completed successfully!"

      # Clean up - revoke temporary security group rule
      - name: Revoke temporary IP access
        if: always() # Run even if previous steps failed
        run: |
          echo "Removing IP ${{ steps.ip.outputs.ipv4 }} from security group $AWS_INSTANCE_SG_ID"
          aws ec2 revoke-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
