name: Generate Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'apps/rathburn-app/src/**'
      - 'apps/rathburn-app/docs/**'
  workflow_dispatch:

jobs:
  generate-docs:
    name: Generate API Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.20"
          
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9.0.0
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Install TypeDoc
        run: pnpm add -w typedoc
        
      - name: Generate API documentation
        run: |
          cd apps/rathburn-app
          npx typedoc --entryPointStrategy expand --out docs/api-docs src/
          
      - name: Create Pull Request with documentation changes
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update API documentation"
          title: "Update API documentation"
          body: |
            This PR updates the API documentation.
            
            Auto-generated by the GitHub Actions workflow.
          branch: update-api-docs
          base: main